# Generated by Django 3.0.8 on 2020-09-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='admin/default.jpg', upload_to='profile_pics'),
        ),
    ]
