# Generated by Django 3.0.8 on 2020-08-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200824_0201'),
        ('blog', '0002_auto_20200825_2231'),
    ]

    operations = [
    ]
